version: "3"
services:
  db:
    image: mysql
    # utf8mb4 https://stackoverflow.com/a/53398381/1778068
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: concerto
      MYSQL_DATABASE: concerto
      MYSQL_USER: concerto
      MYSQL_PASSWORD: concerto
  concerto:
    image: concerto
    ports: 
      - "80:80"
    depends_on: 
      - db
